Remove the "gomobile bind" from .gitlib-ci.yml.
I've tried everything and I can't make this work. It fails during
linking with errors like this:

/home/user/go/pkg/gomobile/ndk-toolchains/arm/bin/arm-linux-androideabi-clang++ -I . -fPIC -marm -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b022=/tmp/go-build -gno-record-gcc-switches -o $WORK/b022/_cgo_.o $WORK/b022/_cgo_main.o $WORK/b022/_x001.o $WORK/b022/_x002.o $WORK/b022/_x003.o $WORK/b022/_x004.o $WORK/b022/_x005.o $WORK/b022/_x006.o $WORK/b022/_x007.o $WORK/b022/_x008.o -static-libstdc++ -L/home/user/go/src/github.com/keroserene/go-webrtc/lib -L/home/user/go/src/github.com/keroserene/go-webrtc/lib -L./lib -lwebrtc-android-arm-magic -lOpenSLES -llog -ldl -pie
/home/user/go/src/github.com/keroserene/go-webrtc/lib/libwebrtc-android-arm-magic.a(audio_format.o):audio_format.cc:function std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >::operator<<(int): error: undefined reference to 'std::__ndk1::ios_base::getloc() const'
/home/user/go/src/github.com/keroserene/go-webrtc/lib/libwebrtc-android-arm-magic.a(audio_format.o):audio_format.cc:function std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >::operator<<(int): error: undefined reference to 'std::__ndk1::locale::use_facet(std::__ndk1::locale::id&) const'
...
/tmp/go-build429242854/b022/_x008.o:peerconnection.cc:function CGO_DeserializeSDP: error: undefined reference to 'webrtc::JsepSessionDescription::JsepSessionDescription(std::string const&)'
/tmp/go-build429242854/b022/_x008.o:peerconnection.cc:function CGO_DeserializeSDP: error: undefined reference to 'webrtc::SdpDeserialize(std::string const&, webrtc::JsepSessionDescription*, webrtc::SdpParseError*)'

The std::__ndk1 and std::string make this look like a C++ ABI
incompatibility error, as if for example libwebrtc-android-arm-magic.a
was built with libc++ and we are now trying to link with libstdc++.
(Reminiscent of the _GLIBCXX_USE_CXX11_ABI errors as well.)

A partial list of things I tried:
- -DANDROID_STL=c++_static
- -DANDROID_STL=c++_shared
- -DANDROID_STL=gnustl_static
- -DANDROID_STL=gnustl_shared
- -stdlib=libc++
- CGO_CXXFLAGS='-I/home/user/go/pkg/gomobile/ndk-toolchains/arm/include/c++/4.9.x/ -I/home/user/go/pkg/gomobile/ndk-toolchains/arm/include/c++/4.9.x/arm-linux-androideabi/' CGO_LDFLAGS='-L/home/user/go/pkg/gomobile/ndk-toolchains/arm/lib64/'
- -static-libstdc++
- Instead of "gomobile init -ndk $ANDROID_NDK_HOME", do it manually with
  a different API version with
  	$ANDROID_NDK_HOME/build/tools/make_standalone_toolchain.py --arch=arm --api=18 --install-dir ~/go/pkg/gomobile/ndk-toolchains/arm/
  https://developer.android.com/ndk/guides/standalone_toolchain#creating_the_toolchain